version: '3.9'

services: 
    postgres:
        image: postgres:13.2
        volumes: 
            - postgres-data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: postgres
            POSTGRES_DB: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - 5432:5432
        networks:
            - application_network

    application:
        build: .
        volumes:
            - ./src:/app
        command: [ "sh", "-c", "python manage.py runserver 0.0.0.0:8000" ]
        user: ${UID:-0}:${GID:-0}
        ports:
            - 8000:8000
        restart: always
        environment:
            DJANGO_DEBUG: "True"
        depends_on:
            - postgres
        networks:
            - application_network

volumes: 
    postgres-data:

networks:
    application_network:
        driver: bridge